CREATE TABLE IF NOT EXISTS scores (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  region TEXT NOT NULL DEFAULT 'Global',
  score INTEGER NOT NULL,
  time_seconds INTEGER NOT NULL DEFAULT 0,
  difficulty TEXT NOT NULL,
  size INTEGER NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
